void _bbdMMin_TribMVA_BasicCheck()
{
//=========Macro generated from canvas: c/A Simple Graph Example
//=========  (Sun Jan 21 09:13:52 2018) by ROOT version6.08/07
   TCanvas *c = new TCanvas("c", "A Simple Graph Example",0,0,700,500);
   gStyle->SetOptStat(0);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: 
   TPad *pad = new TPad("", "",0,0.2,1,1);
   pad->Draw();
   pad->cd();
   pad->Range(-50,-4539.21,450,903302.7);
   pad->SetFillColor(0);
   pad->SetBorderMode(0);
   pad->SetBorderSize(5);
   pad->SetBottomMargin(0.005);
   pad->SetFrameBorderMode(0);
   pad->SetFrameBorderMode(0);
   
   TH1F *h_b_bbdMMin_Data__57 = new TH1F("h_b_bbdMMin_Data__57","",200,0,2000);
   h_b_bbdMMin_Data__57->SetBinContent(1,772948);
   h_b_bbdMMin_Data__57->SetBinError(1,879.1746);
   h_b_bbdMMin_Data__57->SetEntries(772948);
   h_b_bbdMMin_Data__57->SetLineWidth(3);
   h_b_bbdMMin_Data__57->GetXaxis()->SetTitle("#Delta m_{b,b}^{min} [GeV]");
   h_b_bbdMMin_Data__57->GetXaxis()->SetRange(1,40);
   h_b_bbdMMin_Data__57->GetXaxis()->SetLabelFont(42);
   h_b_bbdMMin_Data__57->GetXaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_Data__57->GetXaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_Data__57->GetXaxis()->SetTitleFont(42);
   h_b_bbdMMin_Data__57->GetYaxis()->SetLabelFont(42);
   h_b_bbdMMin_Data__57->GetYaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_Data__57->GetYaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_Data__57->GetYaxis()->SetTitleFont(42);
   h_b_bbdMMin_Data__57->GetZaxis()->SetLabelFont(42);
   h_b_bbdMMin_Data__57->GetZaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_Data__57->GetZaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_Data__57->GetZaxis()->SetTitleFont(42);
   h_b_bbdMMin_Data__57->Draw("e0");
   
   THStack *hs_MC = new THStack();
   hs_MC->SetName("hs_MC");
   hs_MC->SetTitle("");
   
   TH1F *hs_MC_stack_5 = new TH1F("hs_MC_stack_5","",200,0,2000);
   hs_MC_stack_5->SetMinimum(0);
   hs_MC_stack_5->SetMaximum(858678.3);
   hs_MC_stack_5->SetDirectory(0);
   hs_MC_stack_5->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   hs_MC_stack_5->SetLineColor(ci);
   hs_MC_stack_5->GetXaxis()->SetLabelFont(42);
   hs_MC_stack_5->GetXaxis()->SetLabelSize(0.035);
   hs_MC_stack_5->GetXaxis()->SetTitleSize(0.035);
   hs_MC_stack_5->GetXaxis()->SetTitleFont(42);
   hs_MC_stack_5->GetYaxis()->SetLabelFont(42);
   hs_MC_stack_5->GetYaxis()->SetLabelSize(0.035);
   hs_MC_stack_5->GetYaxis()->SetTitleSize(0.035);
   hs_MC_stack_5->GetYaxis()->SetTitleFont(42);
   hs_MC_stack_5->GetZaxis()->SetLabelFont(42);
   hs_MC_stack_5->GetZaxis()->SetLabelSize(0.035);
   hs_MC_stack_5->GetZaxis()->SetTitleSize(0.035);
   hs_MC_stack_5->GetZaxis()->SetTitleFont(42);
   hs_MC->SetHistogram(hs_MC_stack_5);
   
   
   TH1F *h_b_bbdMMin_BGMC_SingleT__58 = new TH1F("h_b_bbdMMin_BGMC_SingleT__58","",200,0,2000);
   h_b_bbdMMin_BGMC_SingleT__58->SetBinContent(1,41029.72);
   h_b_bbdMMin_BGMC_SingleT__58->SetBinError(1,78.86226);
   h_b_bbdMMin_BGMC_SingleT__58->SetEntries(383544);
   h_b_bbdMMin_BGMC_SingleT__58->SetFillColor(2);
   h_b_bbdMMin_BGMC_SingleT__58->SetLineColor(2);
   h_b_bbdMMin_BGMC_SingleT__58->GetXaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_SingleT__58->GetXaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_SingleT__58->GetXaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_SingleT__58->GetXaxis()->SetTitleFont(42);
   h_b_bbdMMin_BGMC_SingleT__58->GetYaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_SingleT__58->GetYaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_SingleT__58->GetYaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_SingleT__58->GetYaxis()->SetTitleFont(42);
   h_b_bbdMMin_BGMC_SingleT__58->GetZaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_SingleT__58->GetZaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_SingleT__58->GetZaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_SingleT__58->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_bbdMMin_BGMC_SingleT,"");
   
   TH1F *h_b_bbdMMin_BGMC_TTJets__59 = new TH1F("h_b_bbdMMin_BGMC_TTJets__59","",200,0,2000);
   h_b_bbdMMin_BGMC_TTJets__59->SetBinContent(1,564397.4);
   h_b_bbdMMin_BGMC_TTJets__59->SetBinError(1,253.8024);
   h_b_bbdMMin_BGMC_TTJets__59->SetEntries(5273400);
   h_b_bbdMMin_BGMC_TTJets__59->SetFillColor(3);
   h_b_bbdMMin_BGMC_TTJets__59->SetLineColor(3);
   h_b_bbdMMin_BGMC_TTJets__59->GetXaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_TTJets__59->GetXaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_TTJets__59->GetXaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_TTJets__59->GetXaxis()->SetTitleFont(42);
   h_b_bbdMMin_BGMC_TTJets__59->GetYaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_TTJets__59->GetYaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_TTJets__59->GetYaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_TTJets__59->GetYaxis()->SetTitleFont(42);
   h_b_bbdMMin_BGMC_TTJets__59->GetZaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_TTJets__59->GetZaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_TTJets__59->GetZaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_TTJets__59->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_bbdMMin_BGMC_TTJets,"");
   
   TH1F *h_b_bbdMMin_BGMC_WJets__60 = new TH1F("h_b_bbdMMin_BGMC_WJets__60","",200,0,2000);
   h_b_bbdMMin_BGMC_WJets__60->SetBinContent(1,130981);
   h_b_bbdMMin_BGMC_WJets__60->SetBinError(1,1839.392);
   h_b_bbdMMin_BGMC_WJets__60->SetEntries(6930);
   h_b_bbdMMin_BGMC_WJets__60->SetFillColor(4);
   h_b_bbdMMin_BGMC_WJets__60->SetLineColor(4);
   h_b_bbdMMin_BGMC_WJets__60->GetXaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_WJets__60->GetXaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_WJets__60->GetXaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_WJets__60->GetXaxis()->SetTitleFont(42);
   h_b_bbdMMin_BGMC_WJets__60->GetYaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_WJets__60->GetYaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_WJets__60->GetYaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_WJets__60->GetYaxis()->SetTitleFont(42);
   h_b_bbdMMin_BGMC_WJets__60->GetZaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_WJets__60->GetZaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_WJets__60->GetZaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_WJets__60->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_bbdMMin_BGMC_WJets,"");
   
   TH1F *h_b_bbdMMin_BGMC_DY__61 = new TH1F("h_b_bbdMMin_BGMC_DY__61","",200,0,2000);
   h_b_bbdMMin_BGMC_DY__61->SetBinContent(1,41268.84);
   h_b_bbdMMin_BGMC_DY__61->SetBinError(1,333.3211);
   h_b_bbdMMin_BGMC_DY__61->SetEntries(48656);
   h_b_bbdMMin_BGMC_DY__61->SetFillColor(5);
   h_b_bbdMMin_BGMC_DY__61->SetLineColor(5);
   h_b_bbdMMin_BGMC_DY__61->GetXaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_DY__61->GetXaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_DY__61->GetXaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_DY__61->GetXaxis()->SetTitleFont(42);
   h_b_bbdMMin_BGMC_DY__61->GetYaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_DY__61->GetYaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_DY__61->GetYaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_DY__61->GetYaxis()->SetTitleFont(42);
   h_b_bbdMMin_BGMC_DY__61->GetZaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_DY__61->GetZaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_DY__61->GetZaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_DY__61->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_bbdMMin_BGMC_DY,"");
   
   TH1F *h_b_bbdMMin_BGMC_TTGZW__62 = new TH1F("h_b_bbdMMin_BGMC_TTGZW__62","",200,0,2000);
   h_b_bbdMMin_BGMC_TTGZW__62->SetBinContent(1,4132.816);
   h_b_bbdMMin_BGMC_TTGZW__62->SetBinError(1,40.12072);
   h_b_bbdMMin_BGMC_TTGZW__62->SetEntries(343063);
   h_b_bbdMMin_BGMC_TTGZW__62->SetFillColor(6);
   h_b_bbdMMin_BGMC_TTGZW__62->SetLineColor(6);
   h_b_bbdMMin_BGMC_TTGZW__62->GetXaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_TTGZW__62->GetXaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_TTGZW__62->GetXaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_TTGZW__62->GetXaxis()->SetTitleFont(42);
   h_b_bbdMMin_BGMC_TTGZW__62->GetYaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_TTGZW__62->GetYaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_TTGZW__62->GetYaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_TTGZW__62->GetYaxis()->SetTitleFont(42);
   h_b_bbdMMin_BGMC_TTGZW__62->GetZaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_TTGZW__62->GetZaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_TTGZW__62->GetZaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_TTGZW__62->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_bbdMMin_BGMC_TTGZW,"");
   
   TH1F *h_b_bbdMMin_BGMC_DiBoson__63 = new TH1F("h_b_bbdMMin_BGMC_DiBoson__63","",200,0,2000);
   h_b_bbdMMin_BGMC_DiBoson__63->SetBinContent(1,2443.948);
   h_b_bbdMMin_BGMC_DiBoson__63->SetBinError(1,26.8134);
   h_b_bbdMMin_BGMC_DiBoson__63->SetEntries(11667);
   h_b_bbdMMin_BGMC_DiBoson__63->SetFillColor(7);
   h_b_bbdMMin_BGMC_DiBoson__63->SetLineColor(7);
   h_b_bbdMMin_BGMC_DiBoson__63->GetXaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_DiBoson__63->GetXaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_DiBoson__63->GetXaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_DiBoson__63->GetXaxis()->SetTitleFont(42);
   h_b_bbdMMin_BGMC_DiBoson__63->GetYaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_DiBoson__63->GetYaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_DiBoson__63->GetYaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_DiBoson__63->GetYaxis()->SetTitleFont(42);
   h_b_bbdMMin_BGMC_DiBoson__63->GetZaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_DiBoson__63->GetZaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_DiBoson__63->GetZaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_DiBoson__63->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_bbdMMin_BGMC_DiBoson,"");
   
   TH1F *h_b_bbdMMin_BGMC_TriBoson__64 = new TH1F("h_b_bbdMMin_BGMC_TriBoson__64","",200,0,2000);
   h_b_bbdMMin_BGMC_TriBoson__64->SetBinContent(1,58.24833);
   h_b_bbdMMin_BGMC_TriBoson__64->SetBinError(1,1.35388);
   h_b_bbdMMin_BGMC_TriBoson__64->SetEntries(3610);
   h_b_bbdMMin_BGMC_TriBoson__64->SetFillColor(8);
   h_b_bbdMMin_BGMC_TriBoson__64->SetLineColor(8);
   h_b_bbdMMin_BGMC_TriBoson__64->GetXaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_TriBoson__64->GetXaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_TriBoson__64->GetXaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_TriBoson__64->GetXaxis()->SetTitleFont(42);
   h_b_bbdMMin_BGMC_TriBoson__64->GetYaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_TriBoson__64->GetYaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_TriBoson__64->GetYaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_TriBoson__64->GetYaxis()->SetTitleFont(42);
   h_b_bbdMMin_BGMC_TriBoson__64->GetZaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_TriBoson__64->GetZaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_TriBoson__64->GetZaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_TriBoson__64->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_bbdMMin_BGMC_TriBoson,"");
   
   TH1F *h_b_bbdMMin_BGMC_QCD__65 = new TH1F("h_b_bbdMMin_BGMC_QCD__65","",200,0,2000);
   h_b_bbdMMin_BGMC_QCD__65->SetBinContent(1,33477.02);
   h_b_bbdMMin_BGMC_QCD__65->SetBinError(1,3525.425);
   h_b_bbdMMin_BGMC_QCD__65->SetEntries(337);
   h_b_bbdMMin_BGMC_QCD__65->SetFillColor(9);
   h_b_bbdMMin_BGMC_QCD__65->SetLineColor(9);
   h_b_bbdMMin_BGMC_QCD__65->GetXaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_QCD__65->GetXaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_QCD__65->GetXaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_QCD__65->GetXaxis()->SetTitleFont(42);
   h_b_bbdMMin_BGMC_QCD__65->GetYaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_QCD__65->GetYaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_QCD__65->GetYaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_QCD__65->GetYaxis()->SetTitleFont(42);
   h_b_bbdMMin_BGMC_QCD__65->GetZaxis()->SetLabelFont(42);
   h_b_bbdMMin_BGMC_QCD__65->GetZaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_BGMC_QCD__65->GetZaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_BGMC_QCD__65->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_bbdMMin_BGMC_QCD,"");
   hs_MC->Draw("same hist");
   
   TH1F *h_b_bbdMMin_Data__66 = new TH1F("h_b_bbdMMin_Data__66","",200,0,2000);
   h_b_bbdMMin_Data__66->SetBinContent(1,772948);
   h_b_bbdMMin_Data__66->SetBinError(1,879.1746);
   h_b_bbdMMin_Data__66->SetEntries(772948);
   h_b_bbdMMin_Data__66->SetLineWidth(3);
   h_b_bbdMMin_Data__66->GetXaxis()->SetTitle("#Delta m_{b,b}^{min} [GeV]");
   h_b_bbdMMin_Data__66->GetXaxis()->SetRange(1,40);
   h_b_bbdMMin_Data__66->GetXaxis()->SetLabelFont(42);
   h_b_bbdMMin_Data__66->GetXaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_Data__66->GetXaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_Data__66->GetXaxis()->SetTitleFont(42);
   h_b_bbdMMin_Data__66->GetYaxis()->SetLabelFont(42);
   h_b_bbdMMin_Data__66->GetYaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_Data__66->GetYaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_Data__66->GetYaxis()->SetTitleFont(42);
   h_b_bbdMMin_Data__66->GetZaxis()->SetLabelFont(42);
   h_b_bbdMMin_Data__66->GetZaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_Data__66->GetZaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_Data__66->GetZaxis()->SetTitleFont(42);
   h_b_bbdMMin_Data__66->Draw("same e0");
   
   TH1F *h_b_bbdMMin_SGMC_Wh20__67 = new TH1F("h_b_bbdMMin_SGMC_Wh20__67","",200,0,2000);
   h_b_bbdMMin_SGMC_Wh20__67->SetBinContent(1,154173.1);
   h_b_bbdMMin_SGMC_Wh20__67->SetBinError(1,1467.525);
   h_b_bbdMMin_SGMC_Wh20__67->SetEntries(12076);

   ci = TColor::GetColor("#000099");
   h_b_bbdMMin_SGMC_Wh20__67->SetLineColor(ci);
   h_b_bbdMMin_SGMC_Wh20__67->SetLineStyle(3);
   h_b_bbdMMin_SGMC_Wh20__67->GetXaxis()->SetLabelFont(42);
   h_b_bbdMMin_SGMC_Wh20__67->GetXaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_SGMC_Wh20__67->GetXaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_SGMC_Wh20__67->GetXaxis()->SetTitleFont(42);
   h_b_bbdMMin_SGMC_Wh20__67->GetYaxis()->SetLabelFont(42);
   h_b_bbdMMin_SGMC_Wh20__67->GetYaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_SGMC_Wh20__67->GetYaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_SGMC_Wh20__67->GetYaxis()->SetTitleFont(42);
   h_b_bbdMMin_SGMC_Wh20__67->GetZaxis()->SetLabelFont(42);
   h_b_bbdMMin_SGMC_Wh20__67->GetZaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_SGMC_Wh20__67->GetZaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_SGMC_Wh20__67->GetZaxis()->SetTitleFont(42);
   h_b_bbdMMin_SGMC_Wh20__67->Draw("same e0");
   
   TH1F *h_b_bbdMMin_SGMC_Wh50__68 = new TH1F("h_b_bbdMMin_SGMC_Wh50__68","",200,0,2000);
   h_b_bbdMMin_SGMC_Wh50__68->SetBinContent(1,229740.3);
   h_b_bbdMMin_SGMC_Wh50__68->SetBinError(1,1762.123);
   h_b_bbdMMin_SGMC_Wh50__68->SetEntries(18484);

   ci = TColor::GetColor("#000099");
   h_b_bbdMMin_SGMC_Wh50__68->SetLineColor(ci);
   h_b_bbdMMin_SGMC_Wh50__68->SetLineStyle(7);
   h_b_bbdMMin_SGMC_Wh50__68->GetXaxis()->SetLabelFont(42);
   h_b_bbdMMin_SGMC_Wh50__68->GetXaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_SGMC_Wh50__68->GetXaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_SGMC_Wh50__68->GetXaxis()->SetTitleFont(42);
   h_b_bbdMMin_SGMC_Wh50__68->GetYaxis()->SetLabelFont(42);
   h_b_bbdMMin_SGMC_Wh50__68->GetYaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_SGMC_Wh50__68->GetYaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_SGMC_Wh50__68->GetYaxis()->SetTitleFont(42);
   h_b_bbdMMin_SGMC_Wh50__68->GetZaxis()->SetLabelFont(42);
   h_b_bbdMMin_SGMC_Wh50__68->GetZaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_SGMC_Wh50__68->GetZaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_SGMC_Wh50__68->GetZaxis()->SetTitleFont(42);
   h_b_bbdMMin_SGMC_Wh50__68->Draw("same e0");
   TLatex *   tex = new TLatex(0.09770115,0.9194915,"CMS Preliminary 2017, 35.9 fb^{-1}, #sqrt{s} = 13 TeV");
tex->SetNDC();
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.6,0.85,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_b_bbdMMin_SGMC_Wh20","Wh(20)","l");

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(3);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_bbdMMin_SGMC_Wh50","Wh(50)","l");

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(7);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_bbdMMin_BGMC_SingleT","SingleT","f");
   entry->SetFillColor(2);
   entry->SetFillStyle(1001);
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_bbdMMin_BGMC_TTJets","TTJets","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_bbdMMin_BGMC_WJets","WJets","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_bbdMMin_BGMC_DY","DY","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_bbdMMin_BGMC_TTGZW","TTGZW","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_bbdMMin_BGMC_DiBoson","DiBoson","f");
   entry->SetFillColor(7);
   entry->SetFillStyle(1001);
   entry->SetLineColor(7);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_bbdMMin_BGMC_TriBoson","TriBoson","f");
   entry->SetFillColor(8);
   entry->SetFillStyle(1001);
   entry->SetLineColor(8);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_bbdMMin_BGMC_QCD","QCD","f");
   entry->SetFillColor(9);
   entry->SetFillStyle(1001);
   entry->SetLineColor(9);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_bbdMMin_Data","Data","l");

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   pad->Modified();
   c->cd();
  
// ------------>Primitives in pad: ratio
   TPad *ratio = new TPad("ratio", "",0,0,1,0.2);
   ratio->Draw();
   ratio->cd();
   ratio->Range(-50,-0.5571429,450,0.3);
   ratio->SetFillColor(0);
   ratio->SetBorderMode(0);
   ratio->SetBorderSize(5);
   ratio->SetTopMargin(0);
   ratio->SetBottomMargin(0.3);
   ratio->SetFrameBorderMode(0);
   ratio->SetFrameBorderMode(0);
   
   TH1F *h_b_bbdMMin_Data_copy__69 = new TH1F("h_b_bbdMMin_Data_copy__69","",200,0,2000);
   h_b_bbdMMin_Data_copy__69->SetBinContent(1,-0.05483185);
   h_b_bbdMMin_Data_copy__69->SetBinError(1,0.005014576);
   h_b_bbdMMin_Data_copy__69->SetMinimum(-0.3);
   h_b_bbdMMin_Data_copy__69->SetMaximum(0.3);
   h_b_bbdMMin_Data_copy__69->SetEntries(0.05483185);
   h_b_bbdMMin_Data_copy__69->SetDirectory(0);
   h_b_bbdMMin_Data_copy__69->SetStats(0);
   h_b_bbdMMin_Data_copy__69->SetLineWidth(3);
   h_b_bbdMMin_Data_copy__69->SetMarkerStyle(7);
   h_b_bbdMMin_Data_copy__69->GetXaxis()->SetTitle("#Delta m_{b,b}^{min} [GeV]");
   h_b_bbdMMin_Data_copy__69->GetXaxis()->SetRange(1,40);
   h_b_bbdMMin_Data_copy__69->GetXaxis()->SetLabelFont(42);
   h_b_bbdMMin_Data_copy__69->GetXaxis()->SetLabelOffset(0.02);
   h_b_bbdMMin_Data_copy__69->GetXaxis()->SetLabelSize(0.14);
   h_b_bbdMMin_Data_copy__69->GetXaxis()->SetTitleSize(0.15);
   h_b_bbdMMin_Data_copy__69->GetXaxis()->SetTickLength(0.12);
   h_b_bbdMMin_Data_copy__69->GetXaxis()->SetTitleFont(42);
   h_b_bbdMMin_Data_copy__69->GetYaxis()->SetTitle("(Data-MC)/MC");
   h_b_bbdMMin_Data_copy__69->GetYaxis()->SetNdivisions(8);
   h_b_bbdMMin_Data_copy__69->GetYaxis()->SetLabelFont(42);
   h_b_bbdMMin_Data_copy__69->GetYaxis()->SetLabelSize(0.07);
   h_b_bbdMMin_Data_copy__69->GetYaxis()->SetTitleSize(0.08);
   h_b_bbdMMin_Data_copy__69->GetYaxis()->SetTitleOffset(0.3);
   h_b_bbdMMin_Data_copy__69->GetYaxis()->SetTitleFont(42);
   h_b_bbdMMin_Data_copy__69->GetZaxis()->SetLabelFont(42);
   h_b_bbdMMin_Data_copy__69->GetZaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_Data_copy__69->GetZaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_Data_copy__69->GetZaxis()->SetTitleFont(42);
   h_b_bbdMMin_Data_copy__69->Draw("");
   
   TH1F *h_b_bbdMMin_Data_copy__70 = new TH1F("h_b_bbdMMin_Data_copy__70","",200,0,2000);
   h_b_bbdMMin_Data_copy__70->SetMinimum(-0.3);
   h_b_bbdMMin_Data_copy__70->SetMaximum(0.3);
   h_b_bbdMMin_Data_copy__70->SetEntries(200);
   h_b_bbdMMin_Data_copy__70->SetDirectory(0);
   h_b_bbdMMin_Data_copy__70->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   h_b_bbdMMin_Data_copy__70->SetLineColor(ci);
   h_b_bbdMMin_Data_copy__70->SetMarkerStyle(7);
   h_b_bbdMMin_Data_copy__70->GetXaxis()->SetTitle("#Delta m_{b,b}^{min} [GeV]");
   h_b_bbdMMin_Data_copy__70->GetXaxis()->SetRange(1,40);
   h_b_bbdMMin_Data_copy__70->GetXaxis()->SetLabelFont(42);
   h_b_bbdMMin_Data_copy__70->GetXaxis()->SetLabelOffset(0.02);
   h_b_bbdMMin_Data_copy__70->GetXaxis()->SetLabelSize(0.14);
   h_b_bbdMMin_Data_copy__70->GetXaxis()->SetTitleSize(0.15);
   h_b_bbdMMin_Data_copy__70->GetXaxis()->SetTickLength(0.12);
   h_b_bbdMMin_Data_copy__70->GetXaxis()->SetTitleFont(42);
   h_b_bbdMMin_Data_copy__70->GetYaxis()->SetTitle("(Data-MC)/MC");
   h_b_bbdMMin_Data_copy__70->GetYaxis()->SetNdivisions(8);
   h_b_bbdMMin_Data_copy__70->GetYaxis()->SetLabelFont(42);
   h_b_bbdMMin_Data_copy__70->GetYaxis()->SetLabelSize(0.07);
   h_b_bbdMMin_Data_copy__70->GetYaxis()->SetTitleSize(0.08);
   h_b_bbdMMin_Data_copy__70->GetYaxis()->SetTitleOffset(0.3);
   h_b_bbdMMin_Data_copy__70->GetYaxis()->SetTitleFont(42);
   h_b_bbdMMin_Data_copy__70->GetZaxis()->SetLabelFont(42);
   h_b_bbdMMin_Data_copy__70->GetZaxis()->SetLabelSize(0.035);
   h_b_bbdMMin_Data_copy__70->GetZaxis()->SetTitleSize(0.035);
   h_b_bbdMMin_Data_copy__70->GetZaxis()->SetTitleFont(42);
   h_b_bbdMMin_Data_copy__70->Draw("same");
   ratio->Modified();
   c->cd();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
