void TribMVAScorr_MVAOut()
{
//=========Macro generated from canvas: c/A Simple Graph Example
//=========  (Wed Nov 22 07:00:45 2017) by ROOT version6.08/07
   TCanvas *c = new TCanvas("c", "A Simple Graph Example",0,0,700,500);
   gStyle->SetOptStat(0);
   c->SetHighLightColor(2);
   c->Range(-0.7500001,-0.7500001,6.75,6.75);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
   c->SetFrameBorderMode(0);
   
   TH2F *CorrelationMatrixS = new TH2F("CorrelationMatrixS","Correlation Matrix (signal)",6,0,6,6,0,6);
   CorrelationMatrixS->SetBinContent(9,100);
   CorrelationMatrixS->SetBinContent(10,23);
   CorrelationMatrixS->SetBinContent(11,81);
   CorrelationMatrixS->SetBinContent(12,-38);
   CorrelationMatrixS->SetBinContent(13,65);
   CorrelationMatrixS->SetBinContent(14,29);
   CorrelationMatrixS->SetBinContent(17,23);
   CorrelationMatrixS->SetBinContent(18,100);
   CorrelationMatrixS->SetBinContent(19,28);
   CorrelationMatrixS->SetBinContent(20,44);
   CorrelationMatrixS->SetBinContent(21,68);
   CorrelationMatrixS->SetBinContent(22,1);
   CorrelationMatrixS->SetBinContent(25,81);
   CorrelationMatrixS->SetBinContent(26,28);
   CorrelationMatrixS->SetBinContent(27,100);
   CorrelationMatrixS->SetBinContent(28,-47);
   CorrelationMatrixS->SetBinContent(29,80);
   CorrelationMatrixS->SetBinContent(30,27);
   CorrelationMatrixS->SetBinContent(33,-38);
   CorrelationMatrixS->SetBinContent(34,44);
   CorrelationMatrixS->SetBinContent(35,-47);
   CorrelationMatrixS->SetBinContent(36,100);
   CorrelationMatrixS->SetBinContent(37,-14);
   CorrelationMatrixS->SetBinContent(38,-24);
   CorrelationMatrixS->SetBinContent(41,65);
   CorrelationMatrixS->SetBinContent(42,68);
   CorrelationMatrixS->SetBinContent(43,80);
   CorrelationMatrixS->SetBinContent(44,-14);
   CorrelationMatrixS->SetBinContent(45,100);
   CorrelationMatrixS->SetBinContent(46,17);
   CorrelationMatrixS->SetBinContent(49,29);
   CorrelationMatrixS->SetBinContent(50,1);
   CorrelationMatrixS->SetBinContent(51,27);
   CorrelationMatrixS->SetBinContent(52,-24);
   CorrelationMatrixS->SetBinContent(53,17);
   CorrelationMatrixS->SetBinContent(54,100);
   CorrelationMatrixS->SetBinError(9,100);
   CorrelationMatrixS->SetBinError(10,48.40913);
   CorrelationMatrixS->SetBinError(11,90.18595);
   CorrelationMatrixS->SetBinError(12,62.32263);
   CorrelationMatrixS->SetBinError(13,81.06433);
   CorrelationMatrixS->SetBinError(14,54.26148);
   CorrelationMatrixS->SetBinError(17,48.40913);
   CorrelationMatrixS->SetBinError(18,100);
   CorrelationMatrixS->SetBinError(19,53.75358);
   CorrelationMatrixS->SetBinError(20,66.45988);
   CorrelationMatrixS->SetBinError(21,82.77726);
   CorrelationMatrixS->SetBinError(22,12.72784);
   CorrelationMatrixS->SetBinError(25,90.18595);
   CorrelationMatrixS->SetBinError(26,53.75358);
   CorrelationMatrixS->SetBinError(27,100);
   CorrelationMatrixS->SetBinError(28,68.63862);
   CorrelationMatrixS->SetBinError(29,89.70509);
   CorrelationMatrixS->SetBinError(30,52.18983);
   CorrelationMatrixS->SetBinError(33,62.32263);
   CorrelationMatrixS->SetBinError(34,66.45988);
   CorrelationMatrixS->SetBinError(35,68.63862);
   CorrelationMatrixS->SetBinError(36,100);
   CorrelationMatrixS->SetBinError(37,38.61595);
   CorrelationMatrixS->SetBinError(38,49.1874);
   CorrelationMatrixS->SetBinError(41,81.06433);
   CorrelationMatrixS->SetBinError(42,82.77726);
   CorrelationMatrixS->SetBinError(43,89.70509);
   CorrelationMatrixS->SetBinError(44,38.61595);
   CorrelationMatrixS->SetBinError(45,100);
   CorrelationMatrixS->SetBinError(46,41.47387);
   CorrelationMatrixS->SetBinError(49,54.26148);
   CorrelationMatrixS->SetBinError(50,12.72784);
   CorrelationMatrixS->SetBinError(51,52.18983);
   CorrelationMatrixS->SetBinError(52,49.1874);
   CorrelationMatrixS->SetBinError(53,41.47387);
   CorrelationMatrixS->SetBinError(54,100);
   CorrelationMatrixS->SetMinimum(-100);
   CorrelationMatrixS->SetMaximum(100);
   CorrelationMatrixS->SetEntries(72);
   CorrelationMatrixS->SetStats(0);
   CorrelationMatrixS->SetContour(20);
   CorrelationMatrixS->SetContourLevel(0,-100);
   CorrelationMatrixS->SetContourLevel(1,-90);
   CorrelationMatrixS->SetContourLevel(2,-80);
   CorrelationMatrixS->SetContourLevel(3,-70);
   CorrelationMatrixS->SetContourLevel(4,-60);
   CorrelationMatrixS->SetContourLevel(5,-50);
   CorrelationMatrixS->SetContourLevel(6,-40);
   CorrelationMatrixS->SetContourLevel(7,-30);
   CorrelationMatrixS->SetContourLevel(8,-20);
   CorrelationMatrixS->SetContourLevel(9,-10);
   CorrelationMatrixS->SetContourLevel(10,0);
   CorrelationMatrixS->SetContourLevel(11,10);
   CorrelationMatrixS->SetContourLevel(12,20);
   CorrelationMatrixS->SetContourLevel(13,30);
   CorrelationMatrixS->SetContourLevel(14,40);
   CorrelationMatrixS->SetContourLevel(15,50);
   CorrelationMatrixS->SetContourLevel(16,60);
   CorrelationMatrixS->SetContourLevel(17,70);
   CorrelationMatrixS->SetContourLevel(18,80);
   CorrelationMatrixS->SetContourLevel(19,90);
   
   TPaletteAxis *palette = new TPaletteAxis(6.0375,0,6.375,6,CorrelationMatrixS);
palette->SetLabelColor(1);
palette->SetLabelFont(42);
palette->SetLabelOffset(0.005);
palette->SetLabelSize(0.035);
palette->SetTitleOffset(1);
palette->SetTitleSize(0.035);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#f9f90e");
   palette->SetFillColor(ci);
   palette->SetFillStyle(1001);
   CorrelationMatrixS->GetListOfFunctions()->Add(palette,"br");

   ci = TColor::GetColor("#000099");
   CorrelationMatrixS->SetLineColor(ci);
   CorrelationMatrixS->SetMarkerColor(0);
   CorrelationMatrixS->SetMarkerSize(1.5);
   CorrelationMatrixS->GetXaxis()->SetBinLabel(1,"WpT");
   CorrelationMatrixS->GetXaxis()->SetBinLabel(2,"Hmass");
   CorrelationMatrixS->GetXaxis()->SetBinLabel(3,"HpT");
   CorrelationMatrixS->GetXaxis()->SetBinLabel(4,"bbdRAve");
   CorrelationMatrixS->GetXaxis()->SetBinLabel(5,"HHt");
   CorrelationMatrixS->GetXaxis()->SetBinLabel(6,"WHdR");
   CorrelationMatrixS->GetXaxis()->SetBit(TAxis::kLabelsDown);
   CorrelationMatrixS->GetXaxis()->SetLabelFont(42);
   CorrelationMatrixS->GetXaxis()->SetLabelOffset(0.011);
   CorrelationMatrixS->GetXaxis()->SetLabelSize(0.055);
   CorrelationMatrixS->GetXaxis()->SetTitleSize(0.035);
   CorrelationMatrixS->GetXaxis()->SetTitleFont(42);
   CorrelationMatrixS->GetYaxis()->SetBinLabel(1,"WpT");
   CorrelationMatrixS->GetYaxis()->SetBinLabel(2,"Hmass");
   CorrelationMatrixS->GetYaxis()->SetBinLabel(3,"HpT");
   CorrelationMatrixS->GetYaxis()->SetBinLabel(4,"bbdRAve");
   CorrelationMatrixS->GetYaxis()->SetBinLabel(5,"HHt");
   CorrelationMatrixS->GetYaxis()->SetBinLabel(6,"WHdR");
   CorrelationMatrixS->GetYaxis()->SetLabelFont(42);
   CorrelationMatrixS->GetYaxis()->SetLabelSize(0.055);
   CorrelationMatrixS->GetYaxis()->SetTitleSize(0.035);
   CorrelationMatrixS->GetYaxis()->SetTitleFont(42);
   CorrelationMatrixS->GetZaxis()->SetLabelFont(42);
   CorrelationMatrixS->GetZaxis()->SetLabelSize(0.035);
   CorrelationMatrixS->GetZaxis()->SetTitleSize(0.035);
   CorrelationMatrixS->GetZaxis()->SetTitleFont(42);
   CorrelationMatrixS->Draw("TEXT COLZ");
   
   TPaveText *pt = new TPaveText(0.2766379,0.9339831,0.7233621,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *AText = pt->AddText("Correlation Matrix (signal)");
   pt->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
