void TribMVABcorr_MVAOut()
{
//=========Macro generated from canvas: c/A Simple Graph Example
//=========  (Wed Nov 22 07:00:45 2017) by ROOT version6.08/07
   TCanvas *c = new TCanvas("c", "A Simple Graph Example",0,0,700,500);
   gStyle->SetOptStat(0);
   c->SetHighLightColor(2);
   c->Range(-0.7500001,-0.7500001,6.75,6.75);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
   c->SetFrameBorderMode(0);
   
   TH2F *CorrelationMatrixB = new TH2F("CorrelationMatrixB","Correlation Matrix (background)",6,0,6,6,0,6);
   CorrelationMatrixB->SetBinContent(9,100);
   CorrelationMatrixB->SetBinContent(10,18);
   CorrelationMatrixB->SetBinContent(11,47);
   CorrelationMatrixB->SetBinContent(12,-14);
   CorrelationMatrixB->SetBinContent(13,32);
   CorrelationMatrixB->SetBinContent(14,19);
   CorrelationMatrixB->SetBinContent(17,18);
   CorrelationMatrixB->SetBinContent(18,100);
   CorrelationMatrixB->SetBinContent(19,30);
   CorrelationMatrixB->SetBinContent(20,43);
   CorrelationMatrixB->SetBinContent(21,78);
   CorrelationMatrixB->SetBinContent(25,47);
   CorrelationMatrixB->SetBinContent(26,30);
   CorrelationMatrixB->SetBinContent(27,100);
   CorrelationMatrixB->SetBinContent(28,-28);
   CorrelationMatrixB->SetBinContent(29,59);
   CorrelationMatrixB->SetBinContent(30,13);
   CorrelationMatrixB->SetBinContent(33,-14);
   CorrelationMatrixB->SetBinContent(34,43);
   CorrelationMatrixB->SetBinContent(35,-28);
   CorrelationMatrixB->SetBinContent(36,100);
   CorrelationMatrixB->SetBinContent(38,-11);
   CorrelationMatrixB->SetBinContent(41,32);
   CorrelationMatrixB->SetBinContent(42,78);
   CorrelationMatrixB->SetBinContent(43,59);
   CorrelationMatrixB->SetBinContent(45,100);
   CorrelationMatrixB->SetBinContent(46,4);
   CorrelationMatrixB->SetBinContent(49,19);
   CorrelationMatrixB->SetBinContent(51,13);
   CorrelationMatrixB->SetBinContent(52,-11);
   CorrelationMatrixB->SetBinContent(53,4);
   CorrelationMatrixB->SetBinContent(54,100);
   CorrelationMatrixB->SetBinError(9,100);
   CorrelationMatrixB->SetBinError(10,42.7706);
   CorrelationMatrixB->SetBinError(11,68.67183);
   CorrelationMatrixB->SetBinError(12,37.46306);
   CorrelationMatrixB->SetBinError(13,56.92442);
   CorrelationMatrixB->SetBinError(14,43.99976);
   CorrelationMatrixB->SetBinError(17,42.7706);
   CorrelationMatrixB->SetBinError(18,100);
   CorrelationMatrixB->SetBinError(19,54.82967);
   CorrelationMatrixB->SetBinError(20,66.32354);
   CorrelationMatrixB->SetBinError(21,88.4095);
   CorrelationMatrixB->SetBinError(22,6.026051);
   CorrelationMatrixB->SetBinError(25,68.67183);
   CorrelationMatrixB->SetBinError(26,54.82967);
   CorrelationMatrixB->SetBinError(27,100);
   CorrelationMatrixB->SetBinError(28,53.34251);
   CorrelationMatrixB->SetBinError(29,77.06897);
   CorrelationMatrixB->SetBinError(30,37.33232);
   CorrelationMatrixB->SetBinError(33,37.46306);
   CorrelationMatrixB->SetBinError(34,66.32354);
   CorrelationMatrixB->SetBinError(35,53.34251);
   CorrelationMatrixB->SetBinError(36,100);
   CorrelationMatrixB->SetBinError(37,5.297601);
   CorrelationMatrixB->SetBinError(38,34.10978);
   CorrelationMatrixB->SetBinError(41,56.92442);
   CorrelationMatrixB->SetBinError(42,88.4095);
   CorrelationMatrixB->SetBinError(43,77.06897);
   CorrelationMatrixB->SetBinError(44,5.297601);
   CorrelationMatrixB->SetBinError(45,100);
   CorrelationMatrixB->SetBinError(46,20.3288);
   CorrelationMatrixB->SetBinError(49,43.99976);
   CorrelationMatrixB->SetBinError(50,6.026051);
   CorrelationMatrixB->SetBinError(51,37.33232);
   CorrelationMatrixB->SetBinError(52,34.10978);
   CorrelationMatrixB->SetBinError(53,20.3288);
   CorrelationMatrixB->SetBinError(54,100);
   CorrelationMatrixB->SetMinimum(-100);
   CorrelationMatrixB->SetMaximum(100);
   CorrelationMatrixB->SetEntries(72);
   CorrelationMatrixB->SetStats(0);
   CorrelationMatrixB->SetContour(20);
   CorrelationMatrixB->SetContourLevel(0,-100);
   CorrelationMatrixB->SetContourLevel(1,-90);
   CorrelationMatrixB->SetContourLevel(2,-80);
   CorrelationMatrixB->SetContourLevel(3,-70);
   CorrelationMatrixB->SetContourLevel(4,-60);
   CorrelationMatrixB->SetContourLevel(5,-50);
   CorrelationMatrixB->SetContourLevel(6,-40);
   CorrelationMatrixB->SetContourLevel(7,-30);
   CorrelationMatrixB->SetContourLevel(8,-20);
   CorrelationMatrixB->SetContourLevel(9,-10);
   CorrelationMatrixB->SetContourLevel(10,0);
   CorrelationMatrixB->SetContourLevel(11,10);
   CorrelationMatrixB->SetContourLevel(12,20);
   CorrelationMatrixB->SetContourLevel(13,30);
   CorrelationMatrixB->SetContourLevel(14,40);
   CorrelationMatrixB->SetContourLevel(15,50);
   CorrelationMatrixB->SetContourLevel(16,60);
   CorrelationMatrixB->SetContourLevel(17,70);
   CorrelationMatrixB->SetContourLevel(18,80);
   CorrelationMatrixB->SetContourLevel(19,90);
   
   TPaletteAxis *palette = new TPaletteAxis(6.0375,0,6.375,6,CorrelationMatrixB);
palette->SetLabelColor(1);
palette->SetLabelFont(42);
palette->SetLabelOffset(0.005);
palette->SetLabelSize(0.035);
palette->SetTitleOffset(1);
palette->SetTitleSize(0.035);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#f9f90e");
   palette->SetFillColor(ci);
   palette->SetFillStyle(1001);
   CorrelationMatrixB->GetListOfFunctions()->Add(palette,"br");

   ci = TColor::GetColor("#000099");
   CorrelationMatrixB->SetLineColor(ci);
   CorrelationMatrixB->SetMarkerColor(0);
   CorrelationMatrixB->SetMarkerSize(1.5);
   CorrelationMatrixB->GetXaxis()->SetBinLabel(1,"WpT");
   CorrelationMatrixB->GetXaxis()->SetBinLabel(2,"Hmass");
   CorrelationMatrixB->GetXaxis()->SetBinLabel(3,"HpT");
   CorrelationMatrixB->GetXaxis()->SetBinLabel(4,"bbdRAve");
   CorrelationMatrixB->GetXaxis()->SetBinLabel(5,"HHt");
   CorrelationMatrixB->GetXaxis()->SetBinLabel(6,"WHdR");
   CorrelationMatrixB->GetXaxis()->SetBit(TAxis::kLabelsDown);
   CorrelationMatrixB->GetXaxis()->SetLabelFont(42);
   CorrelationMatrixB->GetXaxis()->SetLabelOffset(0.011);
   CorrelationMatrixB->GetXaxis()->SetLabelSize(0.055);
   CorrelationMatrixB->GetXaxis()->SetTitleSize(0.035);
   CorrelationMatrixB->GetXaxis()->SetTitleFont(42);
   CorrelationMatrixB->GetYaxis()->SetBinLabel(1,"WpT");
   CorrelationMatrixB->GetYaxis()->SetBinLabel(2,"Hmass");
   CorrelationMatrixB->GetYaxis()->SetBinLabel(3,"HpT");
   CorrelationMatrixB->GetYaxis()->SetBinLabel(4,"bbdRAve");
   CorrelationMatrixB->GetYaxis()->SetBinLabel(5,"HHt");
   CorrelationMatrixB->GetYaxis()->SetBinLabel(6,"WHdR");
   CorrelationMatrixB->GetYaxis()->SetLabelFont(42);
   CorrelationMatrixB->GetYaxis()->SetLabelSize(0.055);
   CorrelationMatrixB->GetYaxis()->SetTitleSize(0.035);
   CorrelationMatrixB->GetYaxis()->SetTitleFont(42);
   CorrelationMatrixB->GetZaxis()->SetLabelFont(42);
   CorrelationMatrixB->GetZaxis()->SetLabelSize(0.035);
   CorrelationMatrixB->GetZaxis()->SetTitleSize(0.035);
   CorrelationMatrixB->GetZaxis()->SetTitleFont(42);
   CorrelationMatrixB->Draw("TEXT COLZ");
   
   TPaveText *pt = new TPaveText(0.2277874,0.9339831,0.7722126,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *AText = pt->AddText("Correlation Matrix (background)");
   pt->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
